{% set version = '0.9.4.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stringdist
  version: {{ version|replace("-", "_") }}

source:
  fn: stringdist_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/stringdist_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stringdist/stringdist_{{ version }}.tar.gz
  sha256: 24120f19a449ab607a816e4e40f46cedf0b74a784dbe2d6d526bdecc2a07e8e1

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - llvm-openmp >=4.0.1        # [osx]

  host:
    - r-base
    - llvm-openmp >=4.0.1        # [osx]

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - llvm-openmp >=4.0.1        # [osx]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('stringdist')"           # [not win]
    - "\"%R%\" -e \"library('stringdist')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/markvanderloo/stringdist
  license: GPL-3
  summary: Implements an approximate string matching version of R's native 'match' function.
    Can calculate various string distances based on edits (Damerau-Levenshtein, Hamming,
    Levenshtein, optimal sting alignment), qgrams (q- gram, cosine, jaccard distance)
    or heuristic metrics (Jaro, Jaro-Winkler). An implementation of soundex is provided
    as well. Distances can be computed between character vectors while taking proper
    care of encoding or between integer vectors representing generic sequences.
  license_family: GPL3

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: stringdist
# Maintainer: Mark van der Loo <mark.vanderloo@gmail.com>
# License: GPL-3
# Title: Approximate String Matching and String Distance Functions
# LazyData: no
# Type: Package
# LazyLoad: yes
# Authors@R: c( person("Mark", "van der Loo", role=c("aut","cre"),email="mark.vanderloo@gmail.com") , person("Jan", "van der Laan", role="ctb"),person("R Core Team","",role=c("ctb")),person("Nick","Logan",role="ctb"))
# Description: Implements an approximate string matching version of R's native 'match' function. Can calculate various string distances based on edits (Damerau-Levenshtein, Hamming, Levenshtein, optimal sting alignment), qgrams (q- gram, cosine, jaccard distance) or heuristic metrics (Jaro, Jaro-Winkler). An implementation of soundex is provided as well. Distances can be computed between character vectors while taking proper care of encoding or between integer vectors representing generic sequences.
# Version: 0.9.4.7
# Depends: R (>= 2.15.3)
# Imports: parallel
# URL: https://github.com/markvanderloo/stringdist
# BugReports: https://github.com/markvanderloo/stringdist/issues
# Date: 2018-03-05
# Suggests: testthat
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2018-03-13 15:45:20 UTC; mark
# Author: Mark van der Loo [aut, cre], Jan van der Laan [ctb], R Core Team [ctb], Nick Logan [ctb]
# Repository: CRAN
# Date/Publication: 2018-03-13 17:12:48 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
