# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BFKvsR+CUIDLHY9SHLkYWFUSbYnl+RgC9nfRZi5YqUV4o247HPV02eHYJLuE3HA6hoSuyuaSLf6gAIVKyrV55IKQWjqjXyt3paPfP6l+O3dw7uZc8EuJwmnDIV1aV9E2L8RnpxJL91wv3bCVX68wAvO13C1mruIysHeyrj8riJMYDNX0+1NhysAhdymf8qcDiDHE/zglQff0f8vWAnA406wK5TFByKCmECaJlx3X8O4hAN4wXYO/e+FFqEpRLWANVew3qrF2LDB/NxsQe1DLL6LVFldh6w7sVpaCqDKyA5ACkljRHFbWlUS4gjaUWEDPxgru3FHUQu3etv8Y4g8mOpmz0H91JLqAYHbenYxCXNF2g3KnlMW7VQS+aU89ic4TtSa93+zBLHub9Jbwpz57jN1Ag3yhx5JgD/xJsZZrESlwIFgovbrhg/KmDPbeBtw0XqrxkGTFPa3sYvrBJmUBH6r4d5+EX0HEjKCmmSz54Kzbn3KVmjX6hmFM0R+CSBA9M3R9y1ByoDwhqmXGdBVsTpVQQhf6MgOrXswbGWOy+h8a/qThwjWkrEroUwEXIQJu5wFlw8/adbgLbJZfB/Nt4DjfA1bglbzjDlRtUs4ve5euxOON4MFcQWbg/xYPNeWpFgUFaizyZ9xs6jh93gKOpYecjaDc0DYNH0YghlP3f54="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
