travis:
  secure:
    BINSTAR_TOKEN: BFKvsR+CUIDLHY9SHLkYWFUSbYnl+RgC9nfRZi5YqUV4o247HPV02eHYJLuE3HA6hoSuyuaSLf6gAIVKyrV55IKQWjqjXyt3paPfP6l+O3dw7uZc8EuJwmnDIV1aV9E2L8RnpxJL91wv3bCVX68wAvO13C1mruIysHeyrj8riJMYDNX0+1NhysAhdymf8qcDiDHE/zglQff0f8vWAnA406wK5TFByKCmECaJlx3X8O4hAN4wXYO/e+FFqEpRLWANVew3qrF2LDB/NxsQe1DLL6LVFldh6w7sVpaCqDKyA5ACkljRHFbWlUS4gjaUWEDPxgru3FHUQu3etv8Y4g8mOpmz0H91JLqAYHbenYxCXNF2g3KnlMW7VQS+aU89ic4TtSa93+zBLHub9Jbwpz57jN1Ag3yhx5JgD/xJsZZrESlwIFgovbrhg/KmDPbeBtw0XqrxkGTFPa3sYvrBJmUBH6r4d5+EX0HEjKCmmSz54Kzbn3KVmjX6hmFM0R+CSBA9M3R9y1ByoDwhqmXGdBVsTpVQQhf6MgOrXswbGWOy+h8a/qThwjWkrEroUwEXIQJu5wFlw8/adbgLbJZfB/Nt4DjfA1bglbzjDlRtUs4ve5euxOON4MFcQWbg/xYPNeWpFgUFaizyZ9xs6jh93gKOpYecjaDc0DYNH0YghlP3f54=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
