travis:
  secure:
    BINSTAR_TOKEN: KoyQ6y7R7C2Q5OKsacItAV3h8j8osaHs9+yz+JyeadqSQ4BqFvx7+Hva+O8z06KoPoj9n4eVCF8nHYDAq9VADd1Kne4/ugMVR1c/PPrrq0BVmOZWnKOw8uTXSo3VbMiMJgdBNvF43z5jEfoByfBU1A3mRzLt0BudHucJwrcRlTehqUAenZfxHC4S00ToTpbij2m8eUnuD4yAx3x+hKJa616goT19ksvAcVY0ladCprWW4Ly8c+fX1iOsnciwPa82kb3ctDDPkbStDHM8yReXnaThoDDEIDDUulO4zgLSGgHN5s3bIklK+CQMxwjbZH9LMw68NFRslDBZiGosDnp04c+wUmFyR78G+0vUCCKzmojNxwgSZr7Yd44LO/6FN178xBvfLQzQxZfPq3dKw/AZY/nsKEr2BkH0O1Nm8jSwsb7br8LY9DbRH/2xprOpFxpzeEtBe2WC1kilhMojSeqL4FFZ/yaw1D1V5+74XNg/TU/THGTwBO+lG7DJJ9GeGNTIyJEOMgCJ+j8FFrTN2fMOpHn+StpfMKESxoJ+WhRo9HJCS2lgUxT2Wo0KQckp+ZG1g4JW506nO8CAiOAVqyuDxQCQl7QjjrgQtThAHgEbtp5tAUdb+mM+2roB7yYPhf5M40m39+OS07TEVRnigrgCS3QF47sMaPPBGe8NmiPGQ78=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
